name = "Uchiyama"
uuid = "f1e6e184-c84e-43be-804c-a9de2d64248a"
authors = ["Pierre Navaro"]
version = "0.1.0"

[compat]
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
