name: PkgPage
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Install Julia
      uses: julia-actions/setup-julia@v2
      with:
        version: 1.5
    - run: julia -e '
            using Pkg;
            Pkg.add(["NodeJS", "PkgPage", "DataFrames"]);
            using NodeJS;
            run(`$(npm_cmd()) install highlight.js purgecss`);
            import PkgPage;
            PkgPage.optimize(input="page", output="")'
    - name: Build and Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v4
      with:
        BRANCH: gh-pages
        FOLDER: page/__site
